# Generated by Django 4.1.1 on 2022-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcus_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcus',
            old_name='points',
            new_name='direction',
        ),
        migrations.AddField(
            model_name='pcus',
            name='start_point',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
